export { Hero, type HeroProps } from './components/hero/hero.tsx'
export { SocialLinks } from './components/social-links/social-links.tsx'
export { useSocialLinks } from './features/social-links/use-social-links.ts'
export { createSocialLinksFixture } from './features/social-links/fixture.ts'
export type { SocialLinksPort } from './features/social-links/port.ts'
