name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          filter: tree:0
      - uses: voidzero-dev/setup-vp@b69666a3d815beb21ce968bbfc9c17e63973986b # v1.8.0
        with:
          cache: true
      - uses: dmno-dev/varlock-action@d739487dc98537137579a7c8fa3dd2c3cab01159 # v1.0.3
        with:
          working-directory: apps/website
      - run: vp check
      - run: vp run -r test
      - run: vp run -r build
